{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure_story.TestLogin object at 0x7fe8b0715af0>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure_story.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1608804643274, "stop": 1608804643274}, {"name": "点击密码", "status": "passed", "start": 1608804643274, "stop": 1608804643274}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"/Users/chenlei/PycharmProjects/pytestProject/test_allure_story.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1608804643275, "stop": 1608804643275}], "attachments": [{"name": "stdout", "source": "35a0a4e1-356f-4af9-9a0c-6895a24fdf89-attachment.txt", "type": "text/plain"}], "start": 1608804643274, "stop": 1608804643275, "uuid": "b5ddb968-9b05-4735-b25b-fc27daa74bab", "historyId": "fbff15c07dd901d8fa492046e1d605b0", "testCaseId": "e09730822751dfbc16dda95738658248", "fullName": "test_allure_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录"}, {"name": "suite", "value": "test_allure_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "rong360deMacBook-Pro-104.local"}, {"name": "thread", "value": "12661-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_story"}]}